#:schema https://api.nuon.co/v1/general/config-schema?type=docker_build

name = "thanksgiving_app"
type = "docker_build"

dockerfile = "Dockerfile"

[public_repo]
repo      = "matt-zach-s/ecs-saas-app"
directory = "."
branch    = "main"
